In [2]:
import pandas as pd 
import numpy as np
import seaborn as sns

In [3]:
customer_data = pd.read_csv(r"C:\Users\jayen\Downloads\shopping_behavior_updated (1).csv")

In [4]:
customer_data.head(2)

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Yes,2,Cash,Fortnightly

In [5]:
customer_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3896 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Discount Applied        3900 non-null   object
 13  Previous Purchases      3900 non-null   int64
 14  Payment Method          3900 non-null   object
 15  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(11)
memory usage: 487.6+ KB

In [6]:
customer_data.describe(include='all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3896.000000,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750719,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716187,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,50.000000,NaN,NaN

In [7]:
customer_data.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             4
Subscription Status       0
Discount Applied          0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [8]:
customer_data['Review Rating'] = customer_data.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [9]:
customer_data.columns = customer_data.columns.str.lower()

In [10]:
customer_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   customer id             3900 non-null   int64
 1   age                     3900 non-null   int64
 2   gender                  3900 non-null   object
 3   item purchased          3900 non-null   object
 4   category                3900 non-null   object
 5   purchase amount (usd)   3900 non-null   int64
 6   location                3900 non-null   object
 7   size                    3900 non-null   object
 8   color                   3900 non-null   object
 9   season                  3900 non-null   object
 10  review rating           3900 non-null   float64
 11  subscription status     3900 non-null   object
 12  discount applied        3900 non-null   object
 13  previous purchases      3900 non-null   int64
 14  payment method          3900 non-null   object
 15  frequency of purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(11)
memory usage: 487.6+ KB

In [11]:
customer_data.columns = customer_data.columns.str.replace(" ","_")

In [12]:
customer_data.head(2)

,customer_id,age,gender,item_purchased,category,purchase_amount_(usd),location,size,color,season,review_rating,subscription_status,discount_applied,previous_purchases,payment_method,frequency_of_purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Yes,2,Cash,Fortnightly

In [13]:
customer_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   customer_id             3900 non-null   int64
 1   age                     3900 non-null   int64
 2   gender                  3900 non-null   object
 3   item_purchased          3900 non-null   object
 4   category                3900 non-null   object
 5   purchase_amount_(usd)   3900 non-null   int64
 6   location                3900 non-null   object
 7   size                    3900 non-null   object
 8   color                   3900 non-null   object
 9   season                  3900 non-null   object
 10  review_rating           3900 non-null   float64
 11  subscription_status     3900 non-null   object
 12  discount_applied        3900 non-null   object
 13  previous_purchases      3900 non-null   int64
 14  payment_method          3900 non-null   object
 15  frequency_of_purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(11)
memory usage: 487.6+ KB

In [14]:
customer_data = customer_data.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [15]:
customer_data.head(2)

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,discount_applied,previous_purchases,payment_method,frequency_of_purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Yes,2,Cash,Fortnightly

In [16]:
### create a column age_group

labels = ['young_adult', 'adult', 'middle_age', 'senior']
customer_data['age_group'] = pd.qcut(customer_data['age'], q=4, labels = labels)

In [17]:
customer_data.head()

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Yes,14,Venmo,Fortnightly,middle_age
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Yes,2,Cash,Fortnightly,young_adult
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Yes,23,Credit Card,Weekly,middle_age
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Yes,49,PayPal,Weekly,young_adult
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Yes,31,PayPal,Annually,middle_age

In [18]:
customer_data[['age', 'age_group', ]].head(11)

    age    age_group
0    55   middle_age
1    19  young_adult
2    50   middle_age
3    21  young_adult
4    45   middle_age
5    46   middle_age
6    63       senior
7    27  young_adult
8    26  young_adult
9    57   middle_age
10   53   middle_age

In [19]:
# create column purchase_frequency_days

frequency_mapping = {
    'Fortnightly': 14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Bi-weekly': 14,
    'Annually': 365,
    'Every 3 months': 90
}
customer_data['purchase_frequency_days'] = customer_data['frequency_of_purchases'].map(frequency_mapping)

In [20]:
customer_data[['purchase_frequency_days','frequency_of_purchases']].head(11)

    purchase_frequency_days frequency_of_purchases
0                      14.0            Fortnightly
1                      14.0            Fortnightly
2                       7.0                 Weekly
3                       7.0                 Weekly
4                     365.0               Annually
5                       7.0                 Weekly
6                      90.0              Quarterly
7                       7.0                 Weekly
8                     365.0               Annually
9                      90.0              Quarterly
10                      NaN              Bi-Weekly

In [21]:
customer_data[['discount_applied','subscription_status']].head(11)

   discount_applied subscription_status
0               Yes                 Yes
1               Yes                 Yes
2               Yes                 Yes
3               Yes                 Yes
4               Yes                 Yes
5               Yes                 Yes
6               Yes                 Yes
7               Yes                 Yes
8               Yes                 Yes
9               Yes                 Yes
10              Yes                 Yes

In [22]:
(customer_data['discount_applied'] == customer_data['subscription_status']).all()

np.False_

In [23]:
pip install psycopg2-binary sqlalchemy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: psycopg2-binary in c:\users\jayen\appdata\roaming\python\python313\site-packages (2.9.11)
Requirement already satisfied: sqlalchemy in i:\ori\coding\new folder\lib\site-packages (2.0.43)
Requirement already satisfied: greenlet>=1 in i:\ori\coding\new folder\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\jayen\appdata\roaming\python\python313\site-packages (from sqlalchemy) (4.12.2)
Note: you may need to restart the kernel to use updated packages.

In [24]:
from sqlalchemy import create_engine



# step1 : Connect to PostgreSQL
# Replace placeholders with your actual details
username = "postgres"      #default user
password = "Tanisha1432"     # password
host = "localhost"         # if running locally
port = "5432"              # default postgreSQL port
database = "customer_behavior"    #the database you created in pgAdmin

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")


# Step 2 : LOad DataFrame into PostgreSQL

table_name = "customer"   # choose any table name
customer_data.to_sql(table_name, engine, if_exists="replace", index= False)

print(f"Data successfully loaded into table '{table_name}' in database  '{database}'.")

Data successfully loaded into table 'customer' in database  'customer_behavior'.